steps:
  # Build backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/id-pagina-riego/backend-riego", "."]
    dir: "backend"

  # Push backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/id-pagina-riego/backend-riego"]

  # Deploy backend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "backend-riego",
        "--image",
        "gcr.io/id-pagina-riego/backend-riego",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

  # Build frontend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/id-pagina-riego/frontend-riego", "."]
    dir: "frontend"

  # Push frontend
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/id-pagina-riego/frontend-riego"]

  # Deploy frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "frontend-riego",
        "--image",
        "gcr.io/id-pagina-riego/frontend-riego",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/id-pagina-riego/backend-riego"
  - "gcr.io/id-pagina-riego/frontend-riego"
